"""Single source of truth for application and research protocol versions."""

APP_VERSION = "4.2.0"
APP_TITLE = f"梅花易數足球AI自主推理系統 v{APP_VERSION}"
SCHEMA_VERSION = "4.2"
CALCULATION_VERSION = "meihua-engine-v4.2.0"
RULE_VERSION = "score-engine-v4.2.0"
PROMPT_VERSION = "meihua-football-ai-v4.2.0"
SCRIPT_VERSION = "hexagram-semantic-script-v2.0.0"
DELIBERATION_VERSION = "blind-hexagram-deliberation-v1.0.0"
RESEARCH_PROTOCOL_VERSION = "football-prior-x-blind-semantic-deliberation-v3"
